version: '3.8'

services:
  redis:
    image: redis
    restart: always
    ports:
      - '16379:6379'
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      DB_NAME: mongo
